server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/auth/**,/api/user/**
        - id: menu-service
          uri: ${MENU_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/menu/**,/api/categories/**,/uploads/**,/api/products/**
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/orders/**,/ws/**,/api/checkout
        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/payment/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
