spring.application.name=order-service

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5434/order_db}
spring.datasource.username=${DB_USER:nowait_user}
spring.datasource.password=${DB_PASSWORD:nowait_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration (Asymmetric Key)
jwt.public-key=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjPxve+U5bS0UusZG5rRc2K5DBCFlky2x6wLycvn1FoLT7jgvr0roY5h2PI2rdd3naR6BIJhsyibz19dlifzAu8DqQlbq8CKTpCrH/NMeSPNbFkWKIfE3QASbfJy1AWKpDRvnlGRfsl+PeoUVxJcDYiJ4C4yeIlGpU1Hu53KnCaKvTrGQlj7/xXBML2vcXQg0lcXyC3gTq+hkRiLfJshfCHm1QmF33SenvXK+irjjU02SkmnZvf/7xJoOkGQN5yCYOrAokYXTQjmp2xTmlAAXbL04kckgQAc+43uNWOmvwV+mOgDgsmJjEe3y5c783+W7tgnZ8jSeMn4gMf6kQlwKgwIDAQAB-----END PUBLIC KEY-----
jwt.expiration=86400000

# Server port
server.port=${PORT:8083}
