spring.application.name=qr-order

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/cafe_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET:94a08da1fecbb6e8b46990538c7b50b2a5a54e9dbd2d7f8a9a6b6f8f53c1b8a9}
jwt.expiration=86400000

# Server port
server.port=${PORT:8080}

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_T35uU1yGOIZMkt}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:7vxaA0RovwKPjr0oXw7i3HZU}
