apiVersion: v1
kind: ConfigMap
metadata:
  name: nowait-config
data:
  DB_HOST: "postgres-cluster"
  DB_PORT: "5432"
  FRONTEND_URL: "http://192.168.49.2:31179"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  MENU_SERVICE_URL: "http://menu-service:8082"
  ORDER_SERVICE_URL: "http://order-service:8083"
  PAYMENT_SERVICE_URL: "http://payment-service:8084"
  JWT_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjPxve+U5bS0UusZG5rRc
    2K5DBCFlky2x6wLycvn1FoLT7jgvr0roY5h2PI2rdd3naR6BIJhsyibz19dlifzA
    u8DqQlbq8CKTpCrH/NMeSPNbFkWKIfE3QASbfJy1AWKpDRvnlGRfsl+PeoUVxJcD
    YiJ4C4yeIlGpU1Hu53KnCaKvTrGQlj7/xXBML2vcXQg0lcXyC3gTq+hkRiLfJshf
    CHm1QmF33SenvXK+irjjU02SkmnZvf/7xJoOkGQN5yCYOrAokYXTQjmp2xTmlAAX
    bL04kckgQAc+43uNWOmvwV+mOgDgsmJjEe3y5c783+W7tgnZ8jSeMn4gMf6kQlwK
    gwIDAQAB
    -----END PUBLIC KEY-----
